Repository retaildevcrews/gitops, pull requests merged in 2021-05, with the labels that each got.

#7 added directories for OCW clusters
  deploy/pre-central/config.json
  deploy/pre-northcentral/config.json
  deploy/pre-westcentral/config.json
Labels: OCW

#9 added ASB base GitOps deploy
  cluster-manifests/README.md
  cluster-manifests/a0008/ingress-network-policy.yaml
  cluster-manifests/a0008/ns-a0008.yaml
  cluster-manifests/a0008/rbac.yaml
  cluster-manifests/cluster-baseline-settings/aad-pod-identity.yaml
  cluster-manifests/cluster-baseline-settings/akv-secrets-store-csi.yaml
  cluster-manifests/cluster-baseline-settings/flux.yaml
  cluster-manifests/cluster-baseline-settings/kured.yaml
  cluster-manifests/cluster-baseline-settings/ns-cluster-baseline-settings.yaml
  cluster-manifests/cluster-baseline-settings/rbac.yaml
  cluster-manifests/cluster-rbac.yaml
  cluster-manifests/kube-system/container-azm-ms-agentconfig.yaml
Labels: OCW

#10 Deleted flux.yaml from cluster-baseline-settings
  cluster-manifests/cluster-baseline-settings/flux.yaml
Labels: Bug, CI/CD, Enhancement, OCW

#8 updated OCW config.json files
  deploy/pre-central/config.json
  deploy/pre-northcentral/config.json
  deploy/pre-westcentral/config.json
Labels: CI/CD, OCW

#11 Added zone, region to config files
  deploy/pre-central/config.json
  deploy/pre-northcentral/config.json
  deploy/pre-westcentral/config.json
Labels: OCW

#12 added shared files for ocw autogitops challenge
  ocw-gitops/baseline/README.md
  ocw-gitops/baseline/cluster-baseline-settings/01-namespace.yaml
  ocw-gitops/baseline/cluster-baseline-settings/03-akv-secrets-store-csi.yaml
  ocw-gitops/baseline/cluster-baseline-settings/04-aad-pod-identity.yaml
  ocw-gitops/baseline/cluster-baseline-settings/05-kured.yaml
  ocw-gitops/baseline/kube-system/container-azm-ms-agentconfig.yaml
  ocw-gitops/ingress/01-namespace.yaml
  ocw-gitops/ingress/03-traefik.yaml
  ocw-gitops/templates/config.json
Labels: OCW

#13 removed unused files
  deploy/bartr/config.json
  deploy/bartr/ngsa/namespace.yaml
  deploy/pre-central/config.json
  deploy/pre-central/ngsa/namespace.yaml
  deploy/pre-northcentral/config.json
  deploy/pre-northcentral/ngsa/namespace.yaml
  deploy/pre-westcentral/config.json
  deploy/pre-westcentral/ngsa/namespace.yaml
  deploy/test/config.json
  deploy/test/ngsa/namespace.yaml
  dev-deploy/mon-dev/ngsa/namespace.yaml
  dev-deploy/mon-dev/ngsa/ngsa-memory.yaml
  dev-deploy/monitoring/config.json
  dev-deploy/monitoring/ngsa/loderunner.txt
  dev-deploy/monitoring/ngsa/namespace.yaml
  ocw-baseline/baseline/README.md
  ocw-baseline/baseline/cluster-baseline-settings/01-namespace.yaml
  ocw-baseline/baseline/cluster-baseline-settings/03-akv-secrets-store-csi.yaml
  ocw-baseline/baseline/cluster-baseline-settings/04-aad-pod-identity.yaml
  ocw-baseline/baseline/cluster-baseline-settings/05-kured.yaml
  ocw-baseline/baseline/kube-system/container-azm-ms-agentconfig.yaml
  ocw-baseline/ingress/01-namespace.yaml
  ocw-baseline/ingress/03-traefik.yaml
  ocw-gitops/templates/config.json
  ocw/namespace.yaml
  ocw/ngsa-memory.yaml
Labels: OCW, TechnicalDebt
